[package]
name = "edgeware-archive"
version = "0.2.1"
authors = ["Andrew Plaza <aplaza@liquidthink.net>"]
edition = "2018"
description = "Indexes Substrate Data"

[dependencies]
anyhow = "1.0"
ctrlc = { version = "3.1.5", features = ["termination"] }
log = "0.4"
serde = "1.0"
structopt = { version = "0.3", features = ["suggestions", "color"] }
toml = "0.5"

edgeware-runtime = { git = "https://github.com/hicommonwealth/edgeware-node", default-features = false, branch = "drew-erup-4" }
edgeware-cli = { git = "https://github.com/hicommonwealth/edgeware-node", branch = "drew-erup-4" }

substrate-archive = { path = "../../substrate-archive" }
